apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bestie-app-servicemonitor
  labels:
    name: bestie-app-servicemonitor
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app: bestie
